apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transfer-money.fullname" . }}
  labels:
    {{- include "transfer-money.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "transfer-money.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "transfer-money.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "transfer-money.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            initialDelaySeconds: 20
            httpGet:
              path: /actuator/health
              port: http
          env:
            - name: spring.datasource.url
              value: {{ .Values.transferMony.dbUrl }}
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: {{ include "transfer-money.fullname" . }}-db-secret
                  key: username
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: {{ include "transfer-money.fullname" . }}-db-secret
                  key: password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
