---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: my-app
spec:
  endpoints:
  - honorLabels: true
    interval: 20s
    path: /actuator/prometheus
    port: http
    scrapeTimeout: 10s
  selector:
    matchLabels:
      app: my-app